### ISSUE TITLE
Demo page returns a 404 error

### ISSUE THREAD

**Issue by ronkok** [hrldcpr/javascript-coroutines#3]
When I navigate to https://x.st/javascript-coroutines/, I get a 404 - Not Found error.

**Comment by hrldcpr** [comment]
Hey thanks for the note, sadly someone stole my x.st domain. I'm trying to get it back, but in the meantime you can see the archived version of that page:

https://web.archive.org/web/20230405092038/https://x.st/javascript-coroutines/

(And if I fail to get x.st back, I'll eventually get a new domain to host this.)

**Comment by ronkok** [comment]
Good luck. It's a helpful page.

**Comment by hrldcpr** [comment]
Here's a new URL
https://polyhedron.party/javascript-coroutines/
